config/routes.rb
Rails.application.routes.draw do
	root 'posts#index'
  resources :posts, param: :url
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	namespace :admin do
		resources :posts, param: :url
		get 'login', to: 'sessions#new'
		post 'login', to: 'sessions#create'
		delete 'logout', to: 'sessions#destroy'
	end
  get '*not_found' => 'application#routing_error'
  post '*not_found' => 'application#routing_error'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	validates :url, presence: true

	def to_param
		url
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	layout 'admin'
	include Admin::SessionsHelper
end

app/controllers/admin/posts_controller.rb
module Admin
	class PostsController < BaseController
		before_action :logged_in_user
		before_action :set_post, only: [:show, :edit, :update, :destroy]

		def index
			@posts = Post.all
		end

		def new
			@post = Post.new
		end

		def create
			@post = Post.new(post_params)
			if @post.save
				redirect_to admin_post_path(@post), notice: '記事作成成功'
			else
				render 'admin/posts/new', notice: '記事作成失敗'
			end
		end

		def show
		end

		def edit
		end

		def update
			if @post.update(post_params)
				redirect_to admin_post_path(@post), notice: '記事更新成功'
			else
				render 'admin/posts/edit', notice: '記事更新失敗'
			end
		end

		def destroy
			@post.destroy
			redirect_to admin_posts_path, notice: '記事削除成功'
		end

		def post_params
			params.require(:post).permit(:title, :url, :image, :excerpt, :body)
		end

		def set_post
			@post = Post.find_by(url: params[:url])
		end
	end
end

app/controllers/admin/sessions_controller.rb
module Admin
  class SessionsController < BaseController
    def new
    end

    def create
      user = User.find_by(email: params[:session][:email].downcase)
      if user && user.authenticate(params[:session][:password])
        login_in user
        redirect_to admin_posts_path
      else
        flash.now[:alert] = 'ログイン情報違います'
        render 'new'
      end
    end

    def destroy
      logout
      redirect_to admin_login_path
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# 例外ハンドル
	unless Rails.env.development?
		rescue_from Exception,                        with: :_render_500
		rescue_from ActiveRecord::RecordNotFound,     with: :_render_404
		rescue_from ActionController::RoutingError,   with: :_render_404
	end

	def routing_error
		raise ActionController::RoutingError, params[:path]
	end

	private

	def _render_404(e = nil)
		logger.info "Rendering 404 with exception: #{e.message}" if e
		render 'errors/error_404', status: :not_found
	end

	def _render_500(e = nil)
		logger.error "Rendering 500 with exception: #{e.message}" if e
		render 'errors/error_500', status: :internal_server_error
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# GET /posts
	# GET /posts.json
	def index
		@posts = Post.all
	end

	# GET /posts/1
	# GET /posts/1.json
	def show
		@post = Post.find_by(url: params[:url])
	end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/sessions_helper.rb
module Admin::SessionsHelper
	def login_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def logout
		session.delete(:user_id)
		@current_user = nil
	end

	def logged_in_user
		unless logged_in?
			flash[:danger] = "Please log in."
			redirect_to admin_login_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def default_meta_tags
		{
			site: 'LIFE ENG',
			title: '記事一覧',
			reverse: true,
			charset: 'utf-8',
			description: '人生をエンジニアリングするをモットーに様々な記事を書いています。',
			keywords: 'Life, Football, Rails,Ruby,プログラミング',
			canonical: request.original_url,
			separator: '|',
			icon: [
				{ href: image_url('icon.jpg')},
				{ href: image_url('icon.jpg'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/jpg' },
			],
			og: {
				site_name: :site,
				title: :title,
				description: :description,
				type: 'website',
				url: request.original_url,
				image: image_url('default.jpg'),
				local: 'ja-JP',
			},
			twitter: {
				card: 'summary_large_image',
				site: '@_shuntakagi',
				image: image_url('default.jpg'),
			}
		}
	end
end

app/helpers/posts_helper.rb
module PostsHelper
	def set_post
		@post = Post.find_by(url: params[:url])
	end
end

app/views/admin/posts/_form.html.erb
<%= form_with(model: [:admin, post], local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: :input_area %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: :input_area %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :excerpt %>
    <%= form.text_area :excerpt, class: :input_area %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, class: :input_area %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %>
<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/index.html.erb
<%= link_to 'New Post', new_admin_post_path %>

<table>
  <thead>
  <tr>
    <td>タイトル</td>
    <td>URL</td>
    <td>作成日</td>
    <td>更新日</td>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.url %></td>
      <td><%= post.created_at.strftime('%Y/%m/%d') %></td>
      <td><%= post.updated_at.strftime('%Y/%m/%d') %></td>
      <td><%= link_to 'Edit', edit_admin_post_path(post) %></td>
      <td><%= link_to 'Destroy', admin_post_path(post), method: :delete, data: { confirm: '削除する?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', admin_posts_path %>

app/views/admin/posts/show.html.erb
<p id="notice"><%= notice %></p>
<p><strong>Title:</strong></p>
<P><%= @post.title %></p>
<p><strong>Url:</strong></p>
<p><%= @post.url %></p>
<p><strong>Image:</strong></p>
<p><%= image_tag @post.image.to_s %></p>
<p><strong>Excerpt:</strong></p>
<p><%= @post.excerpt %></p>
<p><strong>Body:</strong></p>
<p><%= @post.body %></p>
<p><strong>preview:</strong></p>
<p><%= @post.body.html_safe %></p>

<%= link_to 'Back', admin_posts_path %>
<%= link_to 'Edit', edit_admin_post_path(@post) %>

app/views/layouts/_header.html.erb
<header>
	<h1 id='logo'>LIFE ENG</h1>
</header>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
</head>
<body>
<% if logged_in? %>
  <p><%= link_to 'logout', admin_logout_path, method: :delete %></p>
<% end %>
<p><%= link_to 'ブログへ', posts_path, method: :get %></p>
<div class='container'>
  <% if flash.notice.present? %>
    <p class='alert alert-success'><%= flash.notice %></p>
  <% end %>
  <% if flash.alert.present? %>
    <p class='alert alert-danger'><%= flash.alert %></p>
  <% end %>
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://fonts.googleapis.com/css?family=M+PLUS+Rounded+1c&display=swap" rel="stylesheet">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <%= display_meta_tags(default_meta_tags) %>
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-157942363-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-157942363-1');
  </script>
</head>
<body>
<% if logged_in? %>
  <p id='go-to-admin'><%= link_to 'admin画面へ', admin_posts_path %></p>
<% end %>
<% if flash.notice.present? %>
  <p class='alert alert-success'><%= flash.notice %></p>
<% end %>
<% if flash.alert.present? %>
  <p class='alert alert-danger'><%= flash.alert %></p>
<% end %>
<%= render 'layouts/header' %>
<div class='container'>
  <%= yield %>
</div>
</body>
</html>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div id='article-lists'>
  <ul>
    <% @posts.each do |post| %>
      <li class='article-list orange-shadow'>
        <h2 class='article-title'><%= post.title %></h2>
        <%= image_tag post.image.to_s, :class => 'article-img' %>
        <p class='excerpt'><%= post.excerpt %></p>
        <p class='read-more'><%= link_to '続きを読む', post, { class: 'orange-bottom black-shadow' } %></a></p>
      </li>
    <% end %>
  </ul>
</div>

app/views/posts/show.html.erb
<% set_meta_tags title: @post.title, description: @post.body.to_s.gsub(/\r\n|\r|\n|\s|\t/, ""), og: { image: image_url(@post.image) }, twitter: { image: image_url(@post.image) } %>

<ul id='article-operation'>
  <li class='back-to-article-lists'><%= link_to '記事一覧へ', posts_path, { class: 'orange-bottom orange-shadow' } %></li>
</ul>
<div id='article' class='orange-shadow'>
  <p id='article-date'>
    <%= @post.created_at.strftime('%Y/%m/%d') %>
    <% if @post.created_at.to_date != @post.updated_at.to_date %>
      (更新日: <%= @post.updated_at.strftime('%Y/%m/%d') %>)
    <% end %>
  </p>
  <h1 id='article-title'><%= @post.title %></h1>
  <%= image_tag @post.image.to_s, :class => 'article-img' %>
  <div class='article-body'><%= @post.body.html_safe %></div>
</div>